[NOJIRA] Change name of status and branch name check for clarity.  Comment out the action to parse commits for a single check as we are testing out a different action and this one is case-sensitive.

diff --git a/.github/workflows/jira-ticket-lint.yml b/.github/workflows/jira-ticket-lint.yml
--- a/.github/workflows/jira-ticket-lint.yml
+++ b/.github/workflows/jira-ticket-lint.yml
@@ -7,7 +7,7 @@ jobs:
   jira_status_check:
     runs-on: ubuntu-latest
     steps:
-      - name: Test Jira Status Check
+      - name: Jira Branch Name and Status Check
         uses: smarsh/jira-lint@main
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
@@ -29,26 +29,26 @@ jobs:
           allowed-issue-status-categories: |
             In Progress
           fail-on-error: true
-  parse_commits_for_jira_ids:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Parse Jira Keys from Commit
-        id: jira_keys
-        if: always()
-        uses: HighwayThree/jira-extract-issue-keys@master
-        with:
-          is-pull-request: ${{ github.event_name == 'pull_request' }}
-          parse-all-commits: ${{ github.event_name == 'push' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Fail if no Jira Key found in any commit message
-        if: steps.jira_keys.outputs.jira-keys == ''
-        shell: bash
-        run: |
-          echo "At least one commit message must include a Jira Key"
-          echo "BUILD_STATE=failed" >> $GITHUB_ENV
-          exit 1
-      - name: Echo Jira Keys
-        if: steps.jira_keys.outputs.jira-keys != ''
-        shell: bash
-        run: echo ${{steps.jira_keys.outputs.jira-keys}}
+  # parse_commits_for_jira_ids:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Parse Jira Keys from Commit
+  #       id: jira_keys
+  #       if: always()
+  #       uses: HighwayThree/jira-extract-issue-keys@master
+  #       with:
+  #         is-pull-request: ${{ github.event_name == 'pull_request' }}
+  #         parse-all-commits: ${{ github.event_name == 'push' }}
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Fail if no Jira Key found in any commit message
+  #       if: steps.jira_keys.outputs.jira-keys == ''
+  #       shell: bash
+  #       run: |
+  #         echo "At least one commit message must include a Jira Key"
+  #         echo "BUILD_STATE=failed" >> $GITHUB_ENV
+  #         exit 1
+  #     - name: Echo Jira Keys
+  #       if: steps.jira_keys.outputs.jira-keys != ''
+  #       shell: bash
+  #       run: echo ${{steps.jira_keys.outputs.jira-keys}}
